#!/usr/bin/env python3
"""Copy a sticker into stickers/ and append its metadata to index.yaml.

The metadata file should be a single YAML mapping generated by annotate_sticker.py
or written by the agent according to SKILL.md.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import shutil
import yaml

from gif_to_mp4 import convert_gif

SUPPORTED_INPUT = {".gif", ".jpg", ".jpeg", ".png", ".webp", ".mp4"}
SENDABLE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".mp4"}


def load_index(path: Path) -> dict:
    if not path.exists():
        return {
            "version": 1,
            "selection_policy": {
                "default_use": "consider_for_light_emotional_chat",
                "max_intensity_without_explicit_request": 3,
                "avoid_serious_contexts": True,
            },
            "stickers": [],
        }
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    data.setdefault("version", 1)
    data.setdefault("selection_policy", {
        "default_use": "consider_for_light_emotional_chat",
        "max_intensity_without_explicit_request": 3,
        "avoid_serious_contexts": True,
    })
    data.setdefault("stickers", [])
    return data


def unique_id(base_id: str, existing: set[str]) -> str:
    if base_id not in existing:
        return base_id
    i = 2
    while f"{base_id}_{i:02d}" in existing:
        i += 1
    return f"{base_id}_{i:02d}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source_file", type=Path)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--metadata", type=Path, required=True, help="YAML metadata mapping")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    root = args.root.resolve()
    stickers_dir = root / "stickers"
    index_path = root / "index.yaml"

    if not args.source_file.exists():
        raise SystemExit(f"Source file not found: {args.source_file}")

    ext = args.source_file.suffix.lower()
    if ext not in SUPPORTED_INPUT:
        raise SystemExit(f"Unsupported file type: {ext}")

    meta = yaml.safe_load(args.metadata.read_text(encoding="utf-8"))
    if not isinstance(meta, dict):
        raise SystemExit("Metadata must be a YAML mapping")

    index = load_index(index_path)
    existing_ids = {item.get("id") for item in index.get("stickers", []) if isinstance(item, dict)}

    sticker_id = str(meta.get("id") or args.source_file.stem)
    if sticker_id in existing_ids and not args.overwrite:
        new_id = unique_id(sticker_id, existing_ids)
        meta["id"] = new_id
        sticker_id = new_id

    target_ext = ".mp4" if ext == ".gif" else ext
    if target_ext not in SENDABLE_EXTENSIONS:
        raise SystemExit(f"Unsupported sendable file type: {target_ext}")

    target = stickers_dir / f"{sticker_id}{target_ext}"
    stickers_dir.mkdir(parents=True, exist_ok=True)

    if target.exists() and not args.overwrite:
        raise SystemExit(f"Target already exists: {target}")

    if ext == ".gif":
        convert_gif(args.source_file, target, min_duration=1.0, max_duration=2.0, overwrite=True)
    else:
        shutil.copy2(args.source_file, target)

    meta["file"] = f"stickers/{target.name}"
    meta["type"] = target_ext.lstrip(".")

    required = [
        "id", "file", "type", "short_meaning", "emotion", "intent", "tone",
        "intensity", "tags", "suitable_when", "avoid_when",
        "visual_description", "text_on_image"
    ]
    missing = [k for k in required if k not in meta]
    if missing:
        raise SystemExit(f"Metadata missing required fields: {', '.join(missing)}")

    # If overwrite is true, replace existing entry with same id; otherwise append.
    stickers = index.setdefault("stickers", [])
    replaced = False
    if args.overwrite:
        for i, item in enumerate(stickers):
            if isinstance(item, dict) and item.get("id") == sticker_id:
                stickers[i] = meta
                replaced = True
                break
    if not replaced:
        stickers.append(meta)

    index_path.write_text(yaml.safe_dump(index, allow_unicode=True, sort_keys=False), encoding="utf-8")
    print(f"Added {meta['id']} -> {meta['file']}")


if __name__ == "__main__":
    main()
